#!/bin/bash
# ============================================================================
# entrypoint.sh — コンテナ起動時の初期化（冪等: 何度実行しても安全）
# ============================================================================
set -e

echo "[1/5] Python 3.13 + プロジェクト依存関係"
if ! uv python list --only-installed 2>/dev/null | grep -q "3.13"; then
    echo "Installing Python 3.13 via uv..."
    uv python install 3.13
fi

if [ -f /workspace/pyproject.toml ]; then
    echo "Running uv sync (project dependencies)..."
    cd /workspace && uv sync
    cd /workspace
fi

# Pyright（Python LSP）— 冪等: 既にインストール済みならスキップ
if ! command -v pyright-langserver &>/dev/null; then
    echo "Installing Pyright..."
    uv tool install pyright
fi

echo "[2/5] Shell aliases"
if ! grep -q "alias qi=" ~/.bashrc 2>/dev/null; then
    cat >> ~/.bashrc << 'ALIASES'

# --- qdrant-indexer aliases (auto-generated by entrypoint.sh) ---

# qdrant-indexer CLI
alias qi='cd /workspace && uv run qdrant-indexer'

# Python テスト・リント
alias ptr='cd /workspace && uv run pytest tests/ -xvs'
alias ptrc='cd /workspace && uv run pytest tests/ --cov -xvs'
alias rf='cd /workspace && uv run ruff check .'
alias rff='cd /workspace && uv run ruff format .'
alias mp='cd /workspace && uv run mypy src/qdrant_indexer/'

# Git
alias gst="git status"
alias gcom="git commit"
alias gsw="git switch"
alias gb="git branch"
alias ga="git add"

# ターミナルツール
alias lg="lazygit"
alias cat="bat --paging=never"
alias zj="zellij"
alias zjd="zellij --layout dev"

alias c='clear'
ALIASES
fi

echo "[3/5] PATH・エディタ・ターミナル外観設定"
if ! grep -q 'export PATH="$HOME/.local/bin:$PATH"' ~/.bashrc 2>/dev/null; then
    echo 'export PATH="$HOME/.local/bin:$PATH"' >> ~/.bashrc
fi
if ! grep -q 'export EDITOR=' ~/.bashrc 2>/dev/null; then
    cat >> ~/.bashrc << 'EDITOR_VARS'
export EDITOR="hx"
export VISUAL="hx"
EDITOR_VARS
fi

# ターミナル背景色（Solarized Dark）+ プロンプト
if ! grep -q '__git_branch' ~/.bashrc 2>/dev/null; then
    cat >> ~/.bashrc << 'TERMINAL_STYLE'

# --- ターミナル外観 Solarized Dark（auto-generated by entrypoint.sh） ---

# 背景色を Solarized Dark に変更（OSC 11 エスケープシーケンス）
printf '\e]11;#002b36\e\\'

# Git ブランチ名を取得する関数
__git_branch() {
    local branch
    branch=$(git branch --show-current 2>/dev/null)
    if [ -n "$branch" ]; then
        echo " ($branch)"
    fi
}

# プロンプト設定（Solarized Dark パレット）
export PS1='\[\e[38;5;33m\]\u@\h\[\e[0m\] \[\e[38;5;64m\]\w\[\e[38;5;136m\]$(__git_branch)\[\e[0m\]\n\[\e[38;5;37m\]❯\[\e[0m\] '

# bat テーマ（Solarized Dark）
export BAT_THEME="Solarized (dark)"

# fzf 色設定（Solarized Dark）
export FZF_DEFAULT_OPTS="--color=bg:#002b36,fg:#839496,hl:#268bd2,bg+:#073642,fg+:#eee8d5,hl+:#2aa198,info:#b58900,prompt:#859900,pointer:#d33682,marker:#cb4b16,spinner:#268bd2,header:#586e75"

# ls の色表示（Solarized Dark パレット）
export LS_COLORS="di=38;5;33:ln=38;5;136:ex=38;5;64:*.py=38;5;136:*.md=38;5;245:*.yml=38;5;136:*.yaml=38;5;136:*.json=38;5;136:*.toml=38;5;166:*.sh=38;5;64"
alias ls='ls --color=auto'
TERMINAL_STYLE
fi

echo "[4/5] Claude Code memory symlink"
MEMORY_DIR="$HOME/.claude/projects/-workspace/memory"
MEMORY_SRC="/workspace/.claude/memory/MEMORY.md"

if [ -f "$MEMORY_SRC" ]; then
    mkdir -p "$MEMORY_DIR"
    ln -sf "$MEMORY_SRC" "$MEMORY_DIR/MEMORY.md"

    # 初回のみ: current-developer.md マーカー作成
    if [ ! -f "$MEMORY_DIR/current-developer.md" ]; then
        echo "未設定" > "$MEMORY_DIR/current-developer.md"
    fi
fi

echo "[5/5] ツールバージョン表示"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  qdrant-indexer 開発環境"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "uv:          $(uv --version 2>/dev/null | awk '{print $2}' || echo 'N/A')"
echo "Python:      $(uv run python --version 2>/dev/null | awk '{print $2}' || echo 'not yet synced')"
echo "Node.js:     $(node --version 2>/dev/null || echo 'N/A')"
echo "GitHub CLI:  $(gh --version 2>/dev/null | head -1 | awk '{print $3}' || echo 'N/A')"
echo "Helix:       $(hx --version 2>/dev/null | head -1 || echo 'N/A')"
echo "bat:         $(bat --version 2>/dev/null | awk '{print $2}' || echo 'N/A')"
echo "lazygit:     $(lazygit --version 2>/dev/null | head -1 || echo 'N/A')"
echo "yazi:        $(yazi --version 2>/dev/null | awk '{print $2}' || echo 'N/A')"
echo "Zellij:      $(zellij --version 2>/dev/null | awk '{print $2}' || echo 'N/A')"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "初期化完了"
echo ""
exec "$@"
